esphome:
  name: esp-c3-12f
  platformio_options:
    board_build.flash_mode: dio

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf
    version: recommended
    # Custom sdkconfig options
    sdkconfig_options:
      CONFIG_COMPILER_OPTIMIZATION_SIZE: y
    # Advanced tweaking options
    advanced:
      ignore_efuse_mac_crc: false
  variant: esp32c3

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret api_password

ota:
  password: !secret api_password

wifi:
  networks:
  - ssid: !secret wifi_ssid
    password: !secret wifi_password
    priority: 1
  - ssid: !secret ext_ssid
    password: !secret wifi_password
  power_save_mode: none
  manual_ip:
    static_ip: 192.168.1.51
    gateway: 192.168.1.1
    subnet: 255.255.255.0

preferences:
  flash_write_interval: 15min

button:
  - platform: restart
    name: "ESP-C3-12F Restart"
  - platform: shutdown
    name: "ESP-C3-12F Shutdown"

output:
  - platform: ledc
    pin: GPIO3
    id: red_output
  - platform: ledc
    pin: GPIO4
    id: green_output
  - platform: ledc
    pin: GPIO5
    id: blue_output
  - platform: ledc
    pin: GPIO18
    id: hall_night_light


light:
  - platform: rgb
    name: "RGB Lights"
    red: red_output
    green: green_output
    blue: blue_output
    effects:
      - pulse:
      - random:
      - strobe:
      - flicker:
  - platform: monochromatic
    name: "Hall Night Light"
    output: hall_night_light
    restore_mode: RESTORE_DEFAULT_OFF

external_components:
  - source: github://Jorre05/remote_receiver
    components: [ remote_receiver ]

remote_receiver:
  pin:
    number: GPIO6
  tolerance: 50%
  filter: 250us
  idle: 4ms
  buffer_size: 2kb

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO7
      mode: INPUT_PULLUP
      inverted: true
    filters:
      - delayed_on_off: 40ms
    name: "Light Switch"
    on_multi_click:
      - timing: # Click
          - ON for at most 0.25s
          - OFF for at least 0.05s
        then:
         - homeassistant.service:
             service: input_boolean.toggle
             data:
               entity_id: input_boolean.light_switch_click
      - timing: # Hold
          - ON for at least 0.3s
        then:
         - homeassistant.service:
             service: input_boolean.toggle
             data:
               entity_id: input_boolean.light_switch_hold
  - platform: remote_receiver
    filters:
      - delayed_off: 500ms
    name: "RF Power"
    rc_switch_raw:
      code: "100110001101111100000001"
      protocol: 1
  - platform: remote_receiver
    filters:
      - delayed_off: 500ms
    name: "RF Light"
    rc_switch_raw:
      code: "100110001101111100000100"
      protocol: 1
  - platform: remote_receiver
    filters:
      - delayed_off: 500ms
    name: "RF Brightness Up"
    rc_switch_raw:
      code: "100110001101111100000101"
      protocol: 1
  - platform: remote_receiver
    filters:
      - delayed_off: 500ms
    name: "RF Brightness Down"
    rc_switch_raw:
      code: "100110001101111100000110"
      protocol: 1
  - platform: remote_receiver
    filters:
      - delayed_off: 500ms
    name: "RF 100%"
    rc_switch_raw:
      code: "100110001101111100000111"
      protocol: 1
  - platform: remote_receiver
    filters:
      - delayed_off: 500ms
    name: "RF 50%"
    rc_switch_raw:
      code: "100110001101111100001000"
      protocol: 1
  - platform: remote_receiver
    filters:
      - delayed_off: 500ms
    name: "RF 25%"
    rc_switch_raw:
      code: "100110001101111100001001"
      protocol: 1
  - platform: remote_receiver
    filters:
      - delayed_off: 500ms
    name: "RF Mode Up"
    rc_switch_raw:
      code: "100110001101111100001011"
      protocol: 1
  - platform: remote_receiver
    filters:
      - delayed_off: 500ms
    name: "RF Mode Down"
    rc_switch_raw:
      code: "100110001101111100010001"
      protocol: 1
  - platform: remote_receiver
    filters:
      - delayed_off: 500ms
    name: "RF Speed Up"
    rc_switch_raw:
      code: "100110001101111100001111"
      protocol: 1
  - platform: remote_receiver
    filters:
      - delayed_off: 500ms
    name: "RF Speed Down"
    rc_switch_raw:
      code: "100110001101111100001101"
      protocol: 1
  - platform: remote_receiver
    filters:
      - delayed_off: 500ms
    name: "RF Speed Both"
    rc_switch_raw:
      code: "100110001101111100111111"
      protocol: 1
