esphome:
  name: esp-c3-12f
  platformio_options:
    board_build.flash_mode: dio

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf
    version: recommended
    # Custom sdkconfig options
    sdkconfig_options:
      CONFIG_COMPILER_OPTIMIZATION_SIZE: y
    # Advanced tweaking options
    advanced:
      ignore_efuse_mac_crc: false
  variant: esp32c3

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret api_password

ota:
  password: !secret api_password

wifi:
  ssid: !secret ext_ssid
  password: !secret wifi_password
  fast_connect: on
  power_save_mode: none
  manual_ip:
    static_ip: 192.168.1.51
    gateway: 192.168.1.1
    subnet: 255.255.255.0

preferences:
  flash_write_interval: 15min

button:
  - platform: restart
    name: "ESP-C3-12F Restart"

output:
  - platform: ledc
    pin: GPIO3
    id: red_output
  - platform: ledc
    pin: GPIO4
    id: green_output
  - platform: ledc
    pin: GPIO5
    id: blue_output
  - platform: ledc
    pin: GPIO18
    id: hall_night_light


light:
  - platform: rgb
    name: "RGB Lights"
    red: red_output
    green: green_output
    blue: blue_output
    effects:
      - pulse:
      - random:
      - strobe:
      - flicker:
  - platform: monochromatic
    name: "Hall Night Light"
    output: hall_night_light
    restore_mode: RESTORE_DEFAULT_OFF

external_components:
  - source: github://Jorre05/remote_receiver
    components: [ remote_receiver ]

remote_receiver:
  pin:
    number: GPIO6
    inverted: true

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO7
      mode: INPUT_PULLUP
      inverted: true
    filters:
      - delayed_on_off: 20ms
    name: "Light Switch"
    publish_initial_state: true

  - platform: remote_receiver
    name: "RGB Brightness Up"
    nec:
      address: "0xEF00"
      command: "0xFF00"
  - platform: remote_receiver
    name: "RGB Brightness Down"
    nec:
      address: "0xEF00"
      command: "0xFE01"
  - platform: remote_receiver
    name: "RGB Turn Off"
    nec:
      address: "0xEF00"
      command: "0xFD02"
  - platform: remote_receiver
    name: "RGB Turn On"
    nec:
      address: "0xEF00"
      command: "0xFC03"
  - platform: remote_receiver
    name: "RGB Red 1"
    nec:
      address: "0xEF00"
      command: "0xFB04"
  - platform: remote_receiver
    name: "RGB Green 1"
    nec:
      address: "0xEF00"
      command: "0xFA05"
  - platform: remote_receiver
    name: "RGB Blue 1"
    nec:
      address: "0xEF00"
      command: "0xF906"
  - platform: remote_receiver
    name: "RGB White"
    nec:
      address: "0xEF00"
      command: "0xF807"
  - platform: remote_receiver
    name: "RGB Red 2"
    nec:
      address: "0xEF00"
      command: "0xF708"
  - platform: remote_receiver
    name: "RGB Green 2"
    nec:
      address: "0xEF00"
      command: "0xF609"
  - platform: remote_receiver
    name: "RGB Blue 2"
    nec:
      address: "0xEF00"
      command: "0xF50A"
  - platform: remote_receiver
    name: "RGB Flash"
    nec:
      address: "0xEF00"
      command: "0xF40B"
  - platform: remote_receiver
    name: "RGB Red 3"
    nec:
      address: "0xEF00"
      command: "0xF30C"
  - platform: remote_receiver
    name: "RGB Green 3"
    nec:
      address: "0xEF00"
      command: "0xF20D"
  - platform: remote_receiver
    name: "RGB Blue 3"
    nec:
      address: "0xEF00"
      command: "0xF10E"
  - platform: remote_receiver
    name: "RGB Strobe"
    nec:
      address: "0xEF00"
      command: "0xF00F"
  - platform: remote_receiver
    name: "RGB Red 4"
    nec:
      address: "0xEF00"
      command: "0xEF10"
  - platform: remote_receiver
    name: "RGB Green 4"
    nec:
      address: "0xEF00"
      command: "0xEE11"
  - platform: remote_receiver
    name: "RGB Blue 4"
    nec:
      address: "0xEF00"
      command: "0xED12"
  - platform: remote_receiver
    name: "RGB Fade"
    nec:
      address: "0xEF00"
      command: "0xEC13"
  - platform: remote_receiver
    name: "RGB Red 5"
    nec:
      address: "0xEF00"
      command: "0xEB14"
  - platform: remote_receiver
    name: "RGB Green 5"
    nec:
      address: "0xEF00"
      command: "0xEA15"
  - platform: remote_receiver
    name: "RGB Blue 5"
    nec:
      address: "0xEF00"
      command: "0xE916"
  - platform: remote_receiver
    name: "RGB Smooth"
    nec:
      address: "0xEF00"
      command: "0xE817"
