esphome:
  name: esp-c3-12f
  platformio_options:
    board_build.flash_mode: dio

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf
    version: recommended
    # Custom sdkconfig options
    sdkconfig_options:
      CONFIG_COMPILER_OPTIMIZATION_SIZE: y
    # Advanced tweaking options
    advanced:
      ignore_efuse_mac_crc: false
  variant: esp32c3

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret api_password

ota:
  password: !secret api_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: on
  reboot_timeout: 3min
  manual_ip:
    static_ip: 192.168.1.51
    gateway: 192.168.1.1
    subnet: 255.255.255.0

preferences:
  flash_write_interval: 15min

button:
  - platform: restart
    name: "ESP-C3-12F Restart"

output:
  - platform: ledc
    pin: GPIO3
    id: red_output
  - platform: ledc
    pin: GPIO4
    id: green_output
  - platform: ledc
    pin: GPIO5
    id: blue_output
  - platform: ledc
    pin: GPIO18
    id: hall_night_light


light:
  - platform: rgb
    name: "RGB Lights"
    red: red_output
    green: green_output
    blue: blue_output
    effects:
      - pulse:
      - random:
      - strobe:
      - flicker:
  - platform: monochromatic
    name: "Hall Night Light"
    output: hall_night_light
    restore_mode: RESTORE_DEFAULT_OFF

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO8
      mode: INPUT_PULLUP
      inverted: true
    filters:
      - delayed_on_off: 20ms
    name: "Light Switch"
    on_multi_click:
      - timing: # Click
          - ON for at most 0.3s
          - OFF for at least 0.05s
        then:
         - homeassistant.service:
             service: input_boolean.turn_on
             data:
               entity_id: input_boolean.light_switch_click
         - delay: 0.2s
         - homeassistant.service:
             service: input_boolean.turn_off
             data:
               entity_id: input_boolean.light_switch_click
      - timing: # Hold
          - ON for 0.3s to 1s
          - OFF for at least 0.1s
        then:
         - homeassistant.service:
             service: input_boolean.turn_on
             data:
               entity_id: input_boolean.light_switch_hold
         - delay: 0.2s
         - homeassistant.service:
             service: input_boolean.turn_off
             data:
               entity_id: input_boolean.light_switch_hold
      - timing: # Hold Long
          - ON for at least 1s
        then:
         - homeassistant.service:
             service: input_boolean.turn_on
             data:
               entity_id: input_boolean.light_switch_hold_long
         - delay: 0.2s
         - homeassistant.service:
             service: input_boolean.turn_off
             data:
               entity_id: input_boolean.light_switch_hold_long
