esphome:
  name: relayboard

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret api_password

ota:
  password: !secret api_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

switch:
  - platform: gpio
    pin: 0
    name: "Relay"
    inverted: true
    restore_mode: RESTORE_DEFAULT_ON
