esphome:
  name: esp01-closet-fan

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_key

ota:
  password: !secret api_key

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: on
  manual_ip:
    static_ip: 192.168.1.54
    gateway: 192.168.1.1
    subnet: 255.255.255.0

switch:
  - platform: gpio
    pin: 0
    name: "Closet Fan"
    inverted: true
    restore_mode: ALWAYS_ON
