esphome:
  name: hallmotionlight

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret api_password

ota:
  password: !secret api_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  reboot_timeout: 3min

binary_sensor:
  - platform: gpio
    pin: GPIO2
    name: "PIR Sensor"
    device_class: motion

output:
  - platform: esp8266_pwm
    pin: GPIO0
    id: hallmotionlight_led

light:
  - platform: monochromatic
    name: "Hall LED"
    output: hallmotionlight_led
    restore_mode: ALWAYS_ON
