esphome:
  name: lightswitch

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret api_password

ota:
  password: !secret api_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Lightswitch Fallback Hotspot"
    password: "qMwqmk3zHlqR"

captive_portal:
    

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: true
    name: "Light Switch"
    on_multi_click:
      - timing: # Click
          - ON for at most 0.3s
          - OFF for at least 0.05s
        then:
         - homeassistant.service:
             service: input_boolean.turn_on
             data:
               entity_id: input_boolean.lightswitch_click
         - delay: 0.2s
         - homeassistant.service:
             service: input_boolean.turn_off
             data:
               entity_id: input_boolean.lightswitch_click
      - timing: # Hold
          - ON for 0.3s to 1s
          - OFF for at least 0.1s
        then:
         - homeassistant.service:
             service: input_boolean.turn_on
             data:
               entity_id: input_boolean.lightswitch_hold
         - delay: 0.2s
         - homeassistant.service:
             service: input_boolean.turn_off
             data:
               entity_id: input_boolean.lightswitch_hold
      - timing: # Hold Long
          - ON for at least 1.2s
          - OFF for at least 0.1s
        then:
         - homeassistant.service:
             service: input_boolean.turn_on
             data:
               entity_id: input_boolean.lightswitch_holdlong
         - delay: 0.2s
         - homeassistant.service:
             service: input_boolean.turn_off
             data:
               entity_id: input_boolean.lightswitch_holdlong
