esphome:
  name: nodemcu

esp8266:
  board: nodemcuv2

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret api_password

ota:
  password: !secret api_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

output:
  - platform: esp8266_pwm
    pin: D6
    frequency: 1000 Hz
    id: red_output
  - platform: esp8266_pwm
    pin: D7
    frequency: 1000 Hz
    id: green_output
  - platform: esp8266_pwm
    pin: D5
    frequency: 1000 Hz
    id: blue_output

light:
  - platform: rgb
    name: "RGB Lights"
    red: red_output
    green: green_output
    blue: blue_output
    effects:
      - pulse:
      - random:
      - strobe:
      - flicker:
