esphome:
  name: sonoff-s26-r1

esp8266:
  board: esp01_1m
  board_flash_mode: dout

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_key

ota:
  password: !secret ota_key

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: on
  manual_ip:
    static_ip: 192.168.1.53
    gateway: 192.168.1.1
    subnet: 255.255.255.0

button:
  - platform: restart
    name: "Sonoff S26 R1 Restart"

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode:
        input: true
        pullup: true
      inverted: true
    name: "Sonoff S26 R1 Button"
    on_press:
      - switch.toggle: relay

switch:
  - platform: gpio
    name: "Sonoff S26 R1 Relay"
    pin: GPIO12
    id: relay
    restore_mode: ALWAYS_ON

output:
  - platform: esp8266_pwm
    id: green_led
    pin:
      number: GPIO13
      inverted: true

light:
  - platform: monochromatic
    name: "Sonoff S26 R1 Green LED"
    output: green_led
