esphome:
  name: sonoffs26r1-1

esp8266:
  board: esp01_1m
  board_flash_mode: dout

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret api_password

ota:
  password: !secret api_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  reboot_timeout: 3min

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode:
        input: true
        pullup: true
      inverted: true
    name: "Sonoff S26 R1 1 Button"
    on_press:
      - switch.toggle: relay

switch:
  - platform: gpio
    name: "Sonoff S26 R1 1 Relay"
    pin: GPIO12
    id: relay
    restore_mode: ALWAYS_ON

output:
  - platform: esp8266_pwm
    id: sonoffs26r1_1_green_led
    pin:
      number: GPIO13
      inverted: true

light:
  - platform: monochromatic
    name: "Sonoff S26 R1 1 Green LED"
    output: sonoffs26r1_1_green_led
