esphome:
  name: sonoff-basic-r2

esp8266:
  board: esp8285

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_key

ota:
  password: !secret api_key

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: on
  manual_ip:
    static_ip: 192.168.1.52
    gateway: 192.168.1.1
    subnet: 255.255.255.0

button:
  - platform: restart
    name: "Sonoff Basic R2 Restart"

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode:
        input: true
        pullup: true
      inverted: true
    name: "Sonoff Basic R2 Button"
    on_press:
      - switch.toggle: relay

switch:
  - platform: gpio
    name: "Sonoff Basic R2 Relay"
    pin: GPIO12
    id: relay
    restore_mode: RESTORE_DEFAULT_ON

status_led:
  pin:
    number: GPIO13
    inverted: yes
