esphome:
  name: esp01-relay-v4-1

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret api_password

ota:
  password: !secret api_password

wifi:
  networks:
  - ssid: !secret wifi_ssid
    password: !secret wifi_password
    priority: 1
  - ssid: !secret ext_ssid
    password: !secret wifi_password
  power_save_mode: none
  manual_ip:
    static_ip: 192.168.1.54
    gateway: 192.168.1.1
    subnet: 255.255.255.0

switch:
  - platform: gpio
    pin: 0
    name: "ESP-01 Relay"
    inverted: true
    restore_mode: ALWAYS_ON
