esphome:
  name: nodemcu-v2

esp8266:
  board: nodemcuv2

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret api_password

ota:
  password: !secret api_password

wifi:
  networks:
  - ssid: !secret wifi_ssid
    password: !secret wifi_password
    priority: 1
  - ssid: !secret ext_ssid
    password: !secret wifi_password
  power_save_mode: none
  manual_ip:
    static_ip: 192.168.1.54
    gateway: 192.168.1.1
    subnet: 255.255.255.0

button:
  - platform: restart
    name: "NodeMCU V2 Restart"


output:
  - platform: esp8266_pwm
    pin: D7
    id: hall_night_light


light:
  - platform: monochromatic
    name: "Hall Night Light"
    output: hall_night_light
    restore_mode: RESTORE_DEFAULT_OFF

binary_sensor:
  - platform: gpio
    pin:
      number: D5
      mode: INPUT_PULLUP
      inverted: true
    filters:
      - delayed_on_off: 20ms
    name: "Light Switch"
    on_multi_click:
      - timing: # Click
          - ON for at most 0.3s
          - OFF for at least 0.05s
        then:
         - homeassistant.service:
             service: input_boolean.toggle
             data:
               entity_id: input_boolean.light_switch_click
      - timing: # Hold
          - ON for 0.3s to 0.7s
          - OFF for at least 0.1s
        then:
         - homeassistant.service:
             service: input_boolean.toggle
             data:
               entity_id: input_boolean.light_switch_hold
      - timing: # Hold Long
          - ON for at least 0.7s
        then:
         - homeassistant.service:
             service: input_boolean.toggle
             data:
               entity_id: input_boolean.light_switch_hold_long
